<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseRobot" Class="DataClassesInterfaceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\DatabaseRobot.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseRobotConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GameFinancialRow" Member="GameFinancialRows">
    <Type Name="GameFinancialRow">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Robot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ID_Match" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MoneyAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(2050) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PlayerInitiater" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WordCensor" Member="WordCensors">
    <Type Name="WordCensor">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Replacement" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CheckPriority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GameFundingRecord" Member="GameFundingRecords">
    <Type Name="GameFundingRecord">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasBeenProcessed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProcessDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaypalCode" Type="System.String" DbType="NVarChar(550) NOT NULL" CanBeNull="false" />
      <Column Name="UsdAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="GameFundsAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GameTip" Member="GameTips">
    <Type Name="GameTip">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipText" Type="System.String" DbType="NVarChar(2050) NOT NULL" CanBeNull="false" />
      <Column Name="TipHeading" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GeneralSettingRow" Member="GeneralSettingRows">
    <Type Name="GeneralSettingRow">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SettingName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SettingValue" Type="System.String" DbType="NVarChar(2050) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InGameDiscussion" Member="InGameDiscussions">
    <Type Name="InGameDiscussion">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UtcDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(2050) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameStartDateUTC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GameEndDateUTC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ID_BotWinner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasFinished" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="YouTubeID" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Arena" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrizeMoney" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MatchArena" Member="MatchArenas">
    <Type Name="MatchArena">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArenaName" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="ArenaDescription" Type="System.String" DbType="NVarChar(2050) NOT NULL" CanBeNull="false" />
      <Column Name="BuiltInLevelID" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="ExternalURLLocation" Type="System.String" DbType="NVarChar(550) NOT NULL" CanBeNull="false" />
      <Column Name="MatchesPlayedHere" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AssetBundleName" Type="System.String" DbType="NVarChar(1050) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NewReelEvent" Member="NewReelEvents">
    <Type Name="NewReelEvent">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ID_MainRobot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsText" Type="System.String" DbType="NVarChar(3050) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoneyWon" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ResetCode" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ImageExt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsPlayer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SteamID" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerRobot" Member="PlayerRobots">
    <Type Name="PlayerRobot">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RobotName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="GamesPlayed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalKills" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalDeaths" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPoints" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MoneyWon" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PlayerOwner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RobotTemplateImage" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LinesOfCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RobotMatchResult" Member="RobotMatchResults">
    <Type Name="RobotMatchResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Match" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ID_Robot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BulletsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BulletsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RamDamage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Health" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalPoints" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MinutesSurvived" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IsSubmitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TotalKills" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamageReceived" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RobotStat" Member="RobotStats">
    <Type Name="RobotStat">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Robot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CalcRank" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalPoints" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalMatches" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalBulletsFired" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalBulletsHit" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalKills" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalDeaths" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalLinesOfCode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalMultiRobotMatchesPlayed" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalMultiRobotMatchesWon" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalMatchesWon" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TotalDamageReceived" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RatioKillToDeath" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RatioCodeToScore" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RatioWinToLoss" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RatioHitsToMiss" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RatioMultiRobotMatchWinsToLoss" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SteamWalletPaymentRecord" Member="SteamWalletPaymentRecords">
    <Type Name="SteamWalletPaymentRecord">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateStarted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateFinished" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsComplete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WasSuccess" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WasFailed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="USDAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="GameCredits" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ResultText" Type="System.String" DbType="NVarChar(2050) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ThreadForum" Member="ThreadForums">
    <Type Name="ThreadForum">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TotalViews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Heading" Type="System.String" DbType="NVarChar(550) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ThreadReply" Member="ThreadReplies">
    <Type Name="ThreadReply">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Thread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReplyText" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Tutorial" Member="Tutorials">
    <Type Name="Tutorial">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TotalViews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Heading" Type="System.String" DbType="NVarChar(550) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TutorialReply" Member="TutorialReplies">
    <Type Name="TutorialReply">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Thread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Player" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReplyText" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>