#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsSite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GpsDatabase")]
	public partial class DataClassesGpsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void InsertUserInvoiceProduct(UserInvoiceProduct instance);
    partial void UpdateUserInvoiceProduct(UserInvoiceProduct instance);
    partial void DeleteUserInvoiceProduct(UserInvoiceProduct instance);
    partial void InsertCompanyCustomer(CompanyCustomer instance);
    partial void UpdateCompanyCustomer(CompanyCustomer instance);
    partial void DeleteCompanyCustomer(CompanyCustomer instance);
    partial void InsertDeviceRoutePoint(DeviceRoutePoint instance);
    partial void UpdateDeviceRoutePoint(DeviceRoutePoint instance);
    partial void DeleteDeviceRoutePoint(DeviceRoutePoint instance);
    partial void InsertGpsDevice(GpsDevice instance);
    partial void UpdateGpsDevice(GpsDevice instance);
    partial void DeleteGpsDevice(GpsDevice instance);
    partial void InsertGpsTrack(GpsTrack instance);
    partial void UpdateGpsTrack(GpsTrack instance);
    partial void DeleteGpsTrack(GpsTrack instance);
    partial void InsertMobileUser(MobileUser instance);
    partial void UpdateMobileUser(MobileUser instance);
    partial void DeleteMobileUser(MobileUser instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertRobotCommand(RobotCommand instance);
    partial void UpdateRobotCommand(RobotCommand instance);
    partial void DeleteRobotCommand(RobotCommand instance);
    partial void InsertUserInvoice(UserInvoice instance);
    partial void UpdateUserInvoice(UserInvoice instance);
    partial void DeleteUserInvoice(UserInvoice instance);
    #endregion
		
		public DataClassesGpsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GpsDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGpsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGpsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGpsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGpsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<UserInvoiceProduct> UserInvoiceProducts
		{
			get
			{
				return this.GetTable<UserInvoiceProduct>();
			}
		}
		
		public System.Data.Linq.Table<CompanyCustomer> CompanyCustomers
		{
			get
			{
				return this.GetTable<CompanyCustomer>();
			}
		}
		
		public System.Data.Linq.Table<DeviceRoutePoint> DeviceRoutePoints
		{
			get
			{
				return this.GetTable<DeviceRoutePoint>();
			}
		}
		
		public System.Data.Linq.Table<GpsDevice> GpsDevices
		{
			get
			{
				return this.GetTable<GpsDevice>();
			}
		}
		
		public System.Data.Linq.Table<GpsTrack> GpsTracks
		{
			get
			{
				return this.GetTable<GpsTrack>();
			}
		}
		
		public System.Data.Linq.Table<MobileUser> MobileUsers
		{
			get
			{
				return this.GetTable<MobileUser>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<RobotCommand> RobotCommands
		{
			get
			{
				return this.GetTable<RobotCommand>();
			}
		}
		
		public System.Data.Linq.Table<UserInvoice> UserInvoices
		{
			get
			{
				return this.GetTable<UserInvoice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CompanyName;
		
		private string _CompanyDescription;
		
		private double _GPSLon;
		
		private double _GPSLat;
		
		private string _CompanyKey;
		
		private string _Username;
		
		private string _Password;
		
		private string _Address;
		
		private string _PhoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnCompanyDescriptionChanging(string value);
    partial void OnCompanyDescriptionChanged();
    partial void OnGPSLonChanging(double value);
    partial void OnGPSLonChanged();
    partial void OnGPSLatChanging(double value);
    partial void OnGPSLatChanged();
    partial void OnCompanyKeyChanging(string value);
    partial void OnCompanyKeyChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public Company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyDescription", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string CompanyDescription
		{
			get
			{
				return this._CompanyDescription;
			}
			set
			{
				if ((this._CompanyDescription != value))
				{
					this.OnCompanyDescriptionChanging(value);
					this.SendPropertyChanging();
					this._CompanyDescription = value;
					this.SendPropertyChanged("CompanyDescription");
					this.OnCompanyDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSLon", DbType="Float NOT NULL")]
		public double GPSLon
		{
			get
			{
				return this._GPSLon;
			}
			set
			{
				if ((this._GPSLon != value))
				{
					this.OnGPSLonChanging(value);
					this.SendPropertyChanging();
					this._GPSLon = value;
					this.SendPropertyChanged("GPSLon");
					this.OnGPSLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSLat", DbType="Float NOT NULL")]
		public double GPSLat
		{
			get
			{
				return this._GPSLat;
			}
			set
			{
				if ((this._GPSLat != value))
				{
					this.OnGPSLatChanging(value);
					this.SendPropertyChanging();
					this._GPSLat = value;
					this.SendPropertyChanged("GPSLat");
					this.OnGPSLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyKey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CompanyKey
		{
			get
			{
				return this._CompanyKey;
			}
			set
			{
				if ((this._CompanyKey != value))
				{
					this.OnCompanyKeyChanging(value);
					this.SendPropertyChanging();
					this._CompanyKey = value;
					this.SendPropertyChanged("CompanyKey");
					this.OnCompanyKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(550) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInvoiceProduct")]
	public partial class UserInvoiceProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _ID_Product;
		
		private int _ID_Company;
		
		private decimal _PricePerUnitAtTime;
		
		private double _UnitsOrdered;
		
		private decimal _TotalCost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnID_ProductChanging(long value);
    partial void OnID_ProductChanged();
    partial void OnID_CompanyChanging(int value);
    partial void OnID_CompanyChanged();
    partial void OnPricePerUnitAtTimeChanging(decimal value);
    partial void OnPricePerUnitAtTimeChanged();
    partial void OnUnitsOrderedChanging(double value);
    partial void OnUnitsOrderedChanged();
    partial void OnTotalCostChanging(decimal value);
    partial void OnTotalCostChanged();
    #endregion
		
		public UserInvoiceProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Product", DbType="BigInt NOT NULL")]
		public long ID_Product
		{
			get
			{
				return this._ID_Product;
			}
			set
			{
				if ((this._ID_Product != value))
				{
					this.OnID_ProductChanging(value);
					this.SendPropertyChanging();
					this._ID_Product = value;
					this.SendPropertyChanged("ID_Product");
					this.OnID_ProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Company", DbType="Int NOT NULL")]
		public int ID_Company
		{
			get
			{
				return this._ID_Company;
			}
			set
			{
				if ((this._ID_Company != value))
				{
					this.OnID_CompanyChanging(value);
					this.SendPropertyChanging();
					this._ID_Company = value;
					this.SendPropertyChanged("ID_Company");
					this.OnID_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerUnitAtTime", DbType="Decimal(18,2) NOT NULL")]
		public decimal PricePerUnitAtTime
		{
			get
			{
				return this._PricePerUnitAtTime;
			}
			set
			{
				if ((this._PricePerUnitAtTime != value))
				{
					this.OnPricePerUnitAtTimeChanging(value);
					this.SendPropertyChanging();
					this._PricePerUnitAtTime = value;
					this.SendPropertyChanged("PricePerUnitAtTime");
					this.OnPricePerUnitAtTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsOrdered", DbType="Float NOT NULL")]
		public double UnitsOrdered
		{
			get
			{
				return this._UnitsOrdered;
			}
			set
			{
				if ((this._UnitsOrdered != value))
				{
					this.OnUnitsOrderedChanging(value);
					this.SendPropertyChanging();
					this._UnitsOrdered = value;
					this.SendPropertyChanged("UnitsOrdered");
					this.OnUnitsOrderedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCost", DbType="Decimal(18,2) NOT NULL")]
		public decimal TotalCost
		{
			get
			{
				return this._TotalCost;
			}
			set
			{
				if ((this._TotalCost != value))
				{
					this.OnTotalCostChanging(value);
					this.SendPropertyChanging();
					this._TotalCost = value;
					this.SendPropertyChanged("TotalCost");
					this.OnTotalCostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CompanyCustomer")]
	public partial class CompanyCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private int _ID_Company;
		
		private string _ProjectName;
		
		private string _ContactPerson;
		
		private string _Address;
		
		private double _GpsLat;
		
		private double _GpsLon;
		
		private string _CustomerNotes;
		
		private string _NotificationPhoneList;
		
		private string _PhoneNumber;
		
		private string _CustomerCompanyName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnID_CompanyChanging(int value);
    partial void OnID_CompanyChanged();
    partial void OnProjectNameChanging(string value);
    partial void OnProjectNameChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnGpsLatChanging(double value);
    partial void OnGpsLatChanged();
    partial void OnGpsLonChanging(double value);
    partial void OnGpsLonChanged();
    partial void OnCustomerNotesChanging(string value);
    partial void OnCustomerNotesChanged();
    partial void OnNotificationPhoneListChanging(string value);
    partial void OnNotificationPhoneListChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCustomerCompanyNameChanging(string value);
    partial void OnCustomerCompanyNameChanged();
    #endregion
		
		public CompanyCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Company", DbType="Int NOT NULL")]
		public int ID_Company
		{
			get
			{
				return this._ID_Company;
			}
			set
			{
				if ((this._ID_Company != value))
				{
					this.OnID_CompanyChanging(value);
					this.SendPropertyChanging();
					this._ID_Company = value;
					this.SendPropertyChanged("ID_Company");
					this.OnID_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectName", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string ProjectName
		{
			get
			{
				return this._ProjectName;
			}
			set
			{
				if ((this._ProjectName != value))
				{
					this.OnProjectNameChanging(value);
					this.SendPropertyChanging();
					this._ProjectName = value;
					this.SendPropertyChanged("ProjectName");
					this.OnProjectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(2050) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GpsLat", DbType="Float NOT NULL")]
		public double GpsLat
		{
			get
			{
				return this._GpsLat;
			}
			set
			{
				if ((this._GpsLat != value))
				{
					this.OnGpsLatChanging(value);
					this.SendPropertyChanging();
					this._GpsLat = value;
					this.SendPropertyChanged("GpsLat");
					this.OnGpsLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GpsLon", DbType="Float NOT NULL")]
		public double GpsLon
		{
			get
			{
				return this._GpsLon;
			}
			set
			{
				if ((this._GpsLon != value))
				{
					this.OnGpsLonChanging(value);
					this.SendPropertyChanging();
					this._GpsLon = value;
					this.SendPropertyChanged("GpsLon");
					this.OnGpsLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNotes", DbType="NVarChar(3050) NOT NULL", CanBeNull=false)]
		public string CustomerNotes
		{
			get
			{
				return this._CustomerNotes;
			}
			set
			{
				if ((this._CustomerNotes != value))
				{
					this.OnCustomerNotesChanging(value);
					this.SendPropertyChanging();
					this._CustomerNotes = value;
					this.SendPropertyChanged("CustomerNotes");
					this.OnCustomerNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotificationPhoneList", DbType="NVarChar(2050) NOT NULL", CanBeNull=false)]
		public string NotificationPhoneList
		{
			get
			{
				return this._NotificationPhoneList;
			}
			set
			{
				if ((this._NotificationPhoneList != value))
				{
					this.OnNotificationPhoneListChanging(value);
					this.SendPropertyChanging();
					this._NotificationPhoneList = value;
					this.SendPropertyChanged("NotificationPhoneList");
					this.OnNotificationPhoneListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerCompanyName", DbType="NVarChar(550) NOT NULL", CanBeNull=false)]
		public string CustomerCompanyName
		{
			get
			{
				return this._CustomerCompanyName;
			}
			set
			{
				if ((this._CustomerCompanyName != value))
				{
					this.OnCustomerCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerCompanyName = value;
					this.SendPropertyChanged("CustomerCompanyName");
					this.OnCustomerCompanyNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceRoutePoint")]
	public partial class DeviceRoutePoint : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _ID_Device;
		
		private int _OrderIndex;
		
		private double _PointX;
		
		private double _PointY;
		
		private double _DestinationX;
		
		private double _DestinationY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnID_DeviceChanging(long value);
    partial void OnID_DeviceChanged();
    partial void OnOrderIndexChanging(int value);
    partial void OnOrderIndexChanged();
    partial void OnPointXChanging(double value);
    partial void OnPointXChanged();
    partial void OnPointYChanging(double value);
    partial void OnPointYChanged();
    partial void OnDestinationXChanging(double value);
    partial void OnDestinationXChanged();
    partial void OnDestinationYChanging(double value);
    partial void OnDestinationYChanged();
    #endregion
		
		public DeviceRoutePoint()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Device", DbType="BigInt NOT NULL")]
		public long ID_Device
		{
			get
			{
				return this._ID_Device;
			}
			set
			{
				if ((this._ID_Device != value))
				{
					this.OnID_DeviceChanging(value);
					this.SendPropertyChanging();
					this._ID_Device = value;
					this.SendPropertyChanged("ID_Device");
					this.OnID_DeviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderIndex", DbType="Int NOT NULL")]
		public int OrderIndex
		{
			get
			{
				return this._OrderIndex;
			}
			set
			{
				if ((this._OrderIndex != value))
				{
					this.OnOrderIndexChanging(value);
					this.SendPropertyChanging();
					this._OrderIndex = value;
					this.SendPropertyChanged("OrderIndex");
					this.OnOrderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointX", DbType="Float NOT NULL")]
		public double PointX
		{
			get
			{
				return this._PointX;
			}
			set
			{
				if ((this._PointX != value))
				{
					this.OnPointXChanging(value);
					this.SendPropertyChanging();
					this._PointX = value;
					this.SendPropertyChanged("PointX");
					this.OnPointXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointY", DbType="Float NOT NULL")]
		public double PointY
		{
			get
			{
				return this._PointY;
			}
			set
			{
				if ((this._PointY != value))
				{
					this.OnPointYChanging(value);
					this.SendPropertyChanging();
					this._PointY = value;
					this.SendPropertyChanged("PointY");
					this.OnPointYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationX", DbType="Float NOT NULL")]
		public double DestinationX
		{
			get
			{
				return this._DestinationX;
			}
			set
			{
				if ((this._DestinationX != value))
				{
					this.OnDestinationXChanging(value);
					this.SendPropertyChanging();
					this._DestinationX = value;
					this.SendPropertyChanged("DestinationX");
					this.OnDestinationXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationY", DbType="Float NOT NULL")]
		public double DestinationY
		{
			get
			{
				return this._DestinationY;
			}
			set
			{
				if ((this._DestinationY != value))
				{
					this.OnDestinationYChanging(value);
					this.SendPropertyChanging();
					this._DestinationY = value;
					this.SendPropertyChanged("DestinationY");
					this.OnDestinationYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GpsDevice")]
	public partial class GpsDevice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _DeviceID;
		
		private double _Lon;
		
		private double _Lat;
		
		private System.DateTime _EntryUtcDate;
		
		private int _ID_Company;
		
		private string _UpdateKey;
		
		private double _DestinationLon;
		
		private double _DestinationLat;
		
		private bool _HasReachedDestination;
		
		private System.DateTime _DateDestinationReached;
		
		private System.DateTime _DateDestinationSet;
		
		private string _FollowerList;
		
		private string _DestinationAddress;
		
		private double _CurrentSpeedKmph;
		
		private double _CurrentDistanceToDestinationKM;
		
		private string _PhoneNumber;
		
		private string _Password;
		
		private string _PasswordHash;
		
		private string _OTP;
		
		private long _ID_CompanyCustomerAssigned;
		
		private string _PersonName;
		
		private double _EstimatedTrackLength;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnDeviceIDChanging(string value);
    partial void OnDeviceIDChanged();
    partial void OnLonChanging(double value);
    partial void OnLonChanged();
    partial void OnLatChanging(double value);
    partial void OnLatChanged();
    partial void OnEntryUtcDateChanging(System.DateTime value);
    partial void OnEntryUtcDateChanged();
    partial void OnID_CompanyChanging(int value);
    partial void OnID_CompanyChanged();
    partial void OnUpdateKeyChanging(string value);
    partial void OnUpdateKeyChanged();
    partial void OnDestinationLonChanging(double value);
    partial void OnDestinationLonChanged();
    partial void OnDestinationLatChanging(double value);
    partial void OnDestinationLatChanged();
    partial void OnHasReachedDestinationChanging(bool value);
    partial void OnHasReachedDestinationChanged();
    partial void OnDateDestinationReachedChanging(System.DateTime value);
    partial void OnDateDestinationReachedChanged();
    partial void OnDateDestinationSetChanging(System.DateTime value);
    partial void OnDateDestinationSetChanged();
    partial void OnFollowerListChanging(string value);
    partial void OnFollowerListChanged();
    partial void OnDestinationAddressChanging(string value);
    partial void OnDestinationAddressChanged();
    partial void OnCurrentSpeedKmphChanging(double value);
    partial void OnCurrentSpeedKmphChanged();
    partial void OnCurrentDistanceToDestinationKMChanging(double value);
    partial void OnCurrentDistanceToDestinationKMChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnOTPChanging(string value);
    partial void OnOTPChanged();
    partial void OnID_CompanyCustomerAssignedChanging(long value);
    partial void OnID_CompanyCustomerAssignedChanged();
    partial void OnPersonNameChanging(string value);
    partial void OnPersonNameChanged();
    partial void OnEstimatedTrackLengthChanging(double value);
    partial void OnEstimatedTrackLengthChanged();
    #endregion
		
		public GpsDevice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this.OnDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._DeviceID = value;
					this.SendPropertyChanged("DeviceID");
					this.OnDeviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lon", DbType="Float NOT NULL")]
		public double Lon
		{
			get
			{
				return this._Lon;
			}
			set
			{
				if ((this._Lon != value))
				{
					this.OnLonChanging(value);
					this.SendPropertyChanging();
					this._Lon = value;
					this.SendPropertyChanged("Lon");
					this.OnLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Float NOT NULL")]
		public double Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryUtcDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryUtcDate
		{
			get
			{
				return this._EntryUtcDate;
			}
			set
			{
				if ((this._EntryUtcDate != value))
				{
					this.OnEntryUtcDateChanging(value);
					this.SendPropertyChanging();
					this._EntryUtcDate = value;
					this.SendPropertyChanged("EntryUtcDate");
					this.OnEntryUtcDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Company", DbType="Int NOT NULL")]
		public int ID_Company
		{
			get
			{
				return this._ID_Company;
			}
			set
			{
				if ((this._ID_Company != value))
				{
					this.OnID_CompanyChanging(value);
					this.SendPropertyChanging();
					this._ID_Company = value;
					this.SendPropertyChanged("ID_Company");
					this.OnID_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateKey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdateKey
		{
			get
			{
				return this._UpdateKey;
			}
			set
			{
				if ((this._UpdateKey != value))
				{
					this.OnUpdateKeyChanging(value);
					this.SendPropertyChanging();
					this._UpdateKey = value;
					this.SendPropertyChanged("UpdateKey");
					this.OnUpdateKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationLon", DbType="Float NOT NULL")]
		public double DestinationLon
		{
			get
			{
				return this._DestinationLon;
			}
			set
			{
				if ((this._DestinationLon != value))
				{
					this.OnDestinationLonChanging(value);
					this.SendPropertyChanging();
					this._DestinationLon = value;
					this.SendPropertyChanged("DestinationLon");
					this.OnDestinationLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationLat", DbType="Float NOT NULL")]
		public double DestinationLat
		{
			get
			{
				return this._DestinationLat;
			}
			set
			{
				if ((this._DestinationLat != value))
				{
					this.OnDestinationLatChanging(value);
					this.SendPropertyChanging();
					this._DestinationLat = value;
					this.SendPropertyChanged("DestinationLat");
					this.OnDestinationLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasReachedDestination", DbType="Bit NOT NULL")]
		public bool HasReachedDestination
		{
			get
			{
				return this._HasReachedDestination;
			}
			set
			{
				if ((this._HasReachedDestination != value))
				{
					this.OnHasReachedDestinationChanging(value);
					this.SendPropertyChanging();
					this._HasReachedDestination = value;
					this.SendPropertyChanged("HasReachedDestination");
					this.OnHasReachedDestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDestinationReached", DbType="DateTime NOT NULL")]
		public System.DateTime DateDestinationReached
		{
			get
			{
				return this._DateDestinationReached;
			}
			set
			{
				if ((this._DateDestinationReached != value))
				{
					this.OnDateDestinationReachedChanging(value);
					this.SendPropertyChanging();
					this._DateDestinationReached = value;
					this.SendPropertyChanged("DateDestinationReached");
					this.OnDateDestinationReachedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDestinationSet", DbType="DateTime NOT NULL")]
		public System.DateTime DateDestinationSet
		{
			get
			{
				return this._DateDestinationSet;
			}
			set
			{
				if ((this._DateDestinationSet != value))
				{
					this.OnDateDestinationSetChanging(value);
					this.SendPropertyChanging();
					this._DateDestinationSet = value;
					this.SendPropertyChanged("DateDestinationSet");
					this.OnDateDestinationSetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FollowerList", DbType="NVarChar(3050) NOT NULL", CanBeNull=false)]
		public string FollowerList
		{
			get
			{
				return this._FollowerList;
			}
			set
			{
				if ((this._FollowerList != value))
				{
					this.OnFollowerListChanging(value);
					this.SendPropertyChanging();
					this._FollowerList = value;
					this.SendPropertyChanged("FollowerList");
					this.OnFollowerListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationAddress", DbType="NVarChar(3050) NOT NULL", CanBeNull=false)]
		public string DestinationAddress
		{
			get
			{
				return this._DestinationAddress;
			}
			set
			{
				if ((this._DestinationAddress != value))
				{
					this.OnDestinationAddressChanging(value);
					this.SendPropertyChanging();
					this._DestinationAddress = value;
					this.SendPropertyChanged("DestinationAddress");
					this.OnDestinationAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSpeedKmph", DbType="Float NOT NULL")]
		public double CurrentSpeedKmph
		{
			get
			{
				return this._CurrentSpeedKmph;
			}
			set
			{
				if ((this._CurrentSpeedKmph != value))
				{
					this.OnCurrentSpeedKmphChanging(value);
					this.SendPropertyChanging();
					this._CurrentSpeedKmph = value;
					this.SendPropertyChanged("CurrentSpeedKmph");
					this.OnCurrentSpeedKmphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentDistanceToDestinationKM", DbType="Float NOT NULL")]
		public double CurrentDistanceToDestinationKM
		{
			get
			{
				return this._CurrentDistanceToDestinationKM;
			}
			set
			{
				if ((this._CurrentDistanceToDestinationKM != value))
				{
					this.OnCurrentDistanceToDestinationKMChanging(value);
					this.SendPropertyChanging();
					this._CurrentDistanceToDestinationKM = value;
					this.SendPropertyChanged("CurrentDistanceToDestinationKM");
					this.OnCurrentDistanceToDestinationKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="NVarChar(550) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OTP
		{
			get
			{
				return this._OTP;
			}
			set
			{
				if ((this._OTP != value))
				{
					this.OnOTPChanging(value);
					this.SendPropertyChanging();
					this._OTP = value;
					this.SendPropertyChanged("OTP");
					this.OnOTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CompanyCustomerAssigned", DbType="BigInt NOT NULL")]
		public long ID_CompanyCustomerAssigned
		{
			get
			{
				return this._ID_CompanyCustomerAssigned;
			}
			set
			{
				if ((this._ID_CompanyCustomerAssigned != value))
				{
					this.OnID_CompanyCustomerAssignedChanging(value);
					this.SendPropertyChanging();
					this._ID_CompanyCustomerAssigned = value;
					this.SendPropertyChanged("ID_CompanyCustomerAssigned");
					this.OnID_CompanyCustomerAssignedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonName", DbType="NVarChar(350) NOT NULL", CanBeNull=false)]
		public string PersonName
		{
			get
			{
				return this._PersonName;
			}
			set
			{
				if ((this._PersonName != value))
				{
					this.OnPersonNameChanging(value);
					this.SendPropertyChanging();
					this._PersonName = value;
					this.SendPropertyChanged("PersonName");
					this.OnPersonNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimatedTrackLength", DbType="Float NOT NULL")]
		public double EstimatedTrackLength
		{
			get
			{
				return this._EstimatedTrackLength;
			}
			set
			{
				if ((this._EstimatedTrackLength != value))
				{
					this.OnEstimatedTrackLengthChanging(value);
					this.SendPropertyChanging();
					this._EstimatedTrackLength = value;
					this.SendPropertyChanged("EstimatedTrackLength");
					this.OnEstimatedTrackLengthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GpsTrack")]
	public partial class GpsTrack : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _DeviceID;
		
		private double _Lon;
		
		private double _Lat;
		
		private System.DateTime _EntryUtcDate;
		
		private int _ID_Company;
		
		private string _UpdateKey;
		
		private double _CurrentSpeedKmphFromLastPoint;
		
		private double _CurrentDistanceToDestinationKM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnDeviceIDChanging(string value);
    partial void OnDeviceIDChanged();
    partial void OnLonChanging(double value);
    partial void OnLonChanged();
    partial void OnLatChanging(double value);
    partial void OnLatChanged();
    partial void OnEntryUtcDateChanging(System.DateTime value);
    partial void OnEntryUtcDateChanged();
    partial void OnID_CompanyChanging(int value);
    partial void OnID_CompanyChanged();
    partial void OnUpdateKeyChanging(string value);
    partial void OnUpdateKeyChanged();
    partial void OnCurrentSpeedKmphFromLastPointChanging(double value);
    partial void OnCurrentSpeedKmphFromLastPointChanged();
    partial void OnCurrentDistanceToDestinationKMChanging(double value);
    partial void OnCurrentDistanceToDestinationKMChanged();
    #endregion
		
		public GpsTrack()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this.OnDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._DeviceID = value;
					this.SendPropertyChanged("DeviceID");
					this.OnDeviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lon", DbType="Float NOT NULL")]
		public double Lon
		{
			get
			{
				return this._Lon;
			}
			set
			{
				if ((this._Lon != value))
				{
					this.OnLonChanging(value);
					this.SendPropertyChanging();
					this._Lon = value;
					this.SendPropertyChanged("Lon");
					this.OnLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Float NOT NULL")]
		public double Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryUtcDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryUtcDate
		{
			get
			{
				return this._EntryUtcDate;
			}
			set
			{
				if ((this._EntryUtcDate != value))
				{
					this.OnEntryUtcDateChanging(value);
					this.SendPropertyChanging();
					this._EntryUtcDate = value;
					this.SendPropertyChanged("EntryUtcDate");
					this.OnEntryUtcDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Company", DbType="Int NOT NULL")]
		public int ID_Company
		{
			get
			{
				return this._ID_Company;
			}
			set
			{
				if ((this._ID_Company != value))
				{
					this.OnID_CompanyChanging(value);
					this.SendPropertyChanging();
					this._ID_Company = value;
					this.SendPropertyChanged("ID_Company");
					this.OnID_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateKey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdateKey
		{
			get
			{
				return this._UpdateKey;
			}
			set
			{
				if ((this._UpdateKey != value))
				{
					this.OnUpdateKeyChanging(value);
					this.SendPropertyChanging();
					this._UpdateKey = value;
					this.SendPropertyChanged("UpdateKey");
					this.OnUpdateKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSpeedKmphFromLastPoint", DbType="Float NOT NULL")]
		public double CurrentSpeedKmphFromLastPoint
		{
			get
			{
				return this._CurrentSpeedKmphFromLastPoint;
			}
			set
			{
				if ((this._CurrentSpeedKmphFromLastPoint != value))
				{
					this.OnCurrentSpeedKmphFromLastPointChanging(value);
					this.SendPropertyChanging();
					this._CurrentSpeedKmphFromLastPoint = value;
					this.SendPropertyChanged("CurrentSpeedKmphFromLastPoint");
					this.OnCurrentSpeedKmphFromLastPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentDistanceToDestinationKM", DbType="Float NOT NULL")]
		public double CurrentDistanceToDestinationKM
		{
			get
			{
				return this._CurrentDistanceToDestinationKM;
			}
			set
			{
				if ((this._CurrentDistanceToDestinationKM != value))
				{
					this.OnCurrentDistanceToDestinationKMChanging(value);
					this.SendPropertyChanging();
					this._CurrentDistanceToDestinationKM = value;
					this.SendPropertyChanged("CurrentDistanceToDestinationKM");
					this.OnCurrentDistanceToDestinationKMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MobileUser")]
	public partial class MobileUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _FirstName;
		
		private string _Surname;
		
		private string _Email;
		
		private string _PhoneNumber;
		
		private double _WorksiteGPSLon;
		
		private double _WorksiteGPSLat;
		
		private double _CurrentGPSLon;
		
		private double _CurrentGPSLat;
		
		private string _Password;
		
		private string _PasswordHash;
		
		private string _OTP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnWorksiteGPSLonChanging(double value);
    partial void OnWorksiteGPSLonChanged();
    partial void OnWorksiteGPSLatChanging(double value);
    partial void OnWorksiteGPSLatChanged();
    partial void OnCurrentGPSLonChanging(double value);
    partial void OnCurrentGPSLonChanged();
    partial void OnCurrentGPSLatChanging(double value);
    partial void OnCurrentGPSLatChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnOTPChanging(string value);
    partial void OnOTPChanged();
    #endregion
		
		public MobileUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorksiteGPSLon", DbType="Float NOT NULL")]
		public double WorksiteGPSLon
		{
			get
			{
				return this._WorksiteGPSLon;
			}
			set
			{
				if ((this._WorksiteGPSLon != value))
				{
					this.OnWorksiteGPSLonChanging(value);
					this.SendPropertyChanging();
					this._WorksiteGPSLon = value;
					this.SendPropertyChanged("WorksiteGPSLon");
					this.OnWorksiteGPSLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorksiteGPSLat", DbType="Float NOT NULL")]
		public double WorksiteGPSLat
		{
			get
			{
				return this._WorksiteGPSLat;
			}
			set
			{
				if ((this._WorksiteGPSLat != value))
				{
					this.OnWorksiteGPSLatChanging(value);
					this.SendPropertyChanging();
					this._WorksiteGPSLat = value;
					this.SendPropertyChanged("WorksiteGPSLat");
					this.OnWorksiteGPSLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGPSLon", DbType="Float NOT NULL")]
		public double CurrentGPSLon
		{
			get
			{
				return this._CurrentGPSLon;
			}
			set
			{
				if ((this._CurrentGPSLon != value))
				{
					this.OnCurrentGPSLonChanging(value);
					this.SendPropertyChanging();
					this._CurrentGPSLon = value;
					this.SendPropertyChanged("CurrentGPSLon");
					this.OnCurrentGPSLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGPSLat", DbType="Float NOT NULL")]
		public double CurrentGPSLat
		{
			get
			{
				return this._CurrentGPSLat;
			}
			set
			{
				if ((this._CurrentGPSLat != value))
				{
					this.OnCurrentGPSLatChanging(value);
					this.SendPropertyChanging();
					this._CurrentGPSLat = value;
					this.SendPropertyChanged("CurrentGPSLat");
					this.OnCurrentGPSLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="NVarChar(550) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OTP
		{
			get
			{
				return this._OTP;
			}
			set
			{
				if ((this._OTP != value))
				{
					this.OnOTPChanging(value);
					this.SendPropertyChanging();
					this._OTP = value;
					this.SendPropertyChanged("OTP");
					this.OnOTPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _ProductName;
		
		private string _ProductDescription;
		
		private string _PricingType;
		
		private string _PricingUnits;
		
		private decimal _PricePerUnit;
		
		private double _MinUnits;
		
		private double _MaxUnits;
		
		private int _ID_Company;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnProductDescriptionChanging(string value);
    partial void OnProductDescriptionChanged();
    partial void OnPricingTypeChanging(string value);
    partial void OnPricingTypeChanged();
    partial void OnPricingUnitsChanging(string value);
    partial void OnPricingUnitsChanged();
    partial void OnPricePerUnitChanging(decimal value);
    partial void OnPricePerUnitChanged();
    partial void OnMinUnitsChanging(double value);
    partial void OnMinUnitsChanged();
    partial void OnMaxUnitsChanging(double value);
    partial void OnMaxUnitsChanged();
    partial void OnID_CompanyChanging(int value);
    partial void OnID_CompanyChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProductDescription
		{
			get
			{
				return this._ProductDescription;
			}
			set
			{
				if ((this._ProductDescription != value))
				{
					this.OnProductDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ProductDescription = value;
					this.SendPropertyChanged("ProductDescription");
					this.OnProductDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricingType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PricingType
		{
			get
			{
				return this._PricingType;
			}
			set
			{
				if ((this._PricingType != value))
				{
					this.OnPricingTypeChanging(value);
					this.SendPropertyChanging();
					this._PricingType = value;
					this.SendPropertyChanged("PricingType");
					this.OnPricingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricingUnits", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PricingUnits
		{
			get
			{
				return this._PricingUnits;
			}
			set
			{
				if ((this._PricingUnits != value))
				{
					this.OnPricingUnitsChanging(value);
					this.SendPropertyChanging();
					this._PricingUnits = value;
					this.SendPropertyChanged("PricingUnits");
					this.OnPricingUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerUnit", DbType="Decimal(18,2) NOT NULL")]
		public decimal PricePerUnit
		{
			get
			{
				return this._PricePerUnit;
			}
			set
			{
				if ((this._PricePerUnit != value))
				{
					this.OnPricePerUnitChanging(value);
					this.SendPropertyChanging();
					this._PricePerUnit = value;
					this.SendPropertyChanged("PricePerUnit");
					this.OnPricePerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinUnits", DbType="Float NOT NULL")]
		public double MinUnits
		{
			get
			{
				return this._MinUnits;
			}
			set
			{
				if ((this._MinUnits != value))
				{
					this.OnMinUnitsChanging(value);
					this.SendPropertyChanging();
					this._MinUnits = value;
					this.SendPropertyChanged("MinUnits");
					this.OnMinUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxUnits", DbType="Float NOT NULL")]
		public double MaxUnits
		{
			get
			{
				return this._MaxUnits;
			}
			set
			{
				if ((this._MaxUnits != value))
				{
					this.OnMaxUnitsChanging(value);
					this.SendPropertyChanging();
					this._MaxUnits = value;
					this.SendPropertyChanged("MaxUnits");
					this.OnMaxUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Company", DbType="Int NOT NULL")]
		public int ID_Company
		{
			get
			{
				return this._ID_Company;
			}
			set
			{
				if ((this._ID_Company != value))
				{
					this.OnID_CompanyChanging(value);
					this.SendPropertyChanging();
					this._ID_Company = value;
					this.SendPropertyChanged("ID_Company");
					this.OnID_CompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RobotCommand")]
	public partial class RobotCommand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _DeviceID;
		
		private string _TestCommandToSend;
		
		private string _AccessPassword;
		
		private string _TestDataReceived;
		
		private System.DateTime _LastRequestDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnDeviceIDChanging(string value);
    partial void OnDeviceIDChanged();
    partial void OnTestCommandToSendChanging(string value);
    partial void OnTestCommandToSendChanged();
    partial void OnAccessPasswordChanging(string value);
    partial void OnAccessPasswordChanged();
    partial void OnTestDataReceivedChanging(string value);
    partial void OnTestDataReceivedChanged();
    partial void OnLastRequestDateChanging(System.DateTime value);
    partial void OnLastRequestDateChanged();
    #endregion
		
		public RobotCommand()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this.OnDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._DeviceID = value;
					this.SendPropertyChanged("DeviceID");
					this.OnDeviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestCommandToSend", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TestCommandToSend
		{
			get
			{
				return this._TestCommandToSend;
			}
			set
			{
				if ((this._TestCommandToSend != value))
				{
					this.OnTestCommandToSendChanging(value);
					this.SendPropertyChanging();
					this._TestCommandToSend = value;
					this.SendPropertyChanged("TestCommandToSend");
					this.OnTestCommandToSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessPassword", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AccessPassword
		{
			get
			{
				return this._AccessPassword;
			}
			set
			{
				if ((this._AccessPassword != value))
				{
					this.OnAccessPasswordChanging(value);
					this.SendPropertyChanging();
					this._AccessPassword = value;
					this.SendPropertyChanged("AccessPassword");
					this.OnAccessPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestDataReceived", DbType="NVarChar(3000) NOT NULL", CanBeNull=false)]
		public string TestDataReceived
		{
			get
			{
				return this._TestDataReceived;
			}
			set
			{
				if ((this._TestDataReceived != value))
				{
					this.OnTestDataReceivedChanging(value);
					this.SendPropertyChanging();
					this._TestDataReceived = value;
					this.SendPropertyChanged("TestDataReceived");
					this.OnTestDataReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastRequestDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastRequestDate
		{
			get
			{
				return this._LastRequestDate;
			}
			set
			{
				if ((this._LastRequestDate != value))
				{
					this.OnLastRequestDateChanging(value);
					this.SendPropertyChanging();
					this._LastRequestDate = value;
					this.SendPropertyChanged("LastRequestDate");
					this.OnLastRequestDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInvoice")]
	public partial class UserInvoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _ID_MobileUser;
		
		private int _ID_Company;
		
		private System.DateTime _CreateDate;
		
		private bool _IsComplete;
		
		private System.DateTime _LastUpdateDate;
		
		private double _DestinationGPSLon;
		
		private double _DestinationGPSLat;
		
		private string _DestinationAddress;
		
		private bool _IsPaid;
		
		private decimal _CostWithoutTransport;
		
		private decimal _TransportCost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnID_MobileUserChanging(long value);
    partial void OnID_MobileUserChanged();
    partial void OnID_CompanyChanging(int value);
    partial void OnID_CompanyChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnIsCompleteChanging(bool value);
    partial void OnIsCompleteChanged();
    partial void OnLastUpdateDateChanging(System.DateTime value);
    partial void OnLastUpdateDateChanged();
    partial void OnDestinationGPSLonChanging(double value);
    partial void OnDestinationGPSLonChanged();
    partial void OnDestinationGPSLatChanging(double value);
    partial void OnDestinationGPSLatChanged();
    partial void OnDestinationAddressChanging(string value);
    partial void OnDestinationAddressChanged();
    partial void OnIsPaidChanging(bool value);
    partial void OnIsPaidChanged();
    partial void OnCostWithoutTransportChanging(decimal value);
    partial void OnCostWithoutTransportChanged();
    partial void OnTransportCostChanging(decimal value);
    partial void OnTransportCostChanged();
    #endregion
		
		public UserInvoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MobileUser", DbType="BigInt NOT NULL")]
		public long ID_MobileUser
		{
			get
			{
				return this._ID_MobileUser;
			}
			set
			{
				if ((this._ID_MobileUser != value))
				{
					this.OnID_MobileUserChanging(value);
					this.SendPropertyChanging();
					this._ID_MobileUser = value;
					this.SendPropertyChanged("ID_MobileUser");
					this.OnID_MobileUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Company", DbType="Int NOT NULL")]
		public int ID_Company
		{
			get
			{
				return this._ID_Company;
			}
			set
			{
				if ((this._ID_Company != value))
				{
					this.OnID_CompanyChanging(value);
					this.SendPropertyChanging();
					this._ID_Company = value;
					this.SendPropertyChanged("ID_Company");
					this.OnID_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit NOT NULL")]
		public bool IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this.OnIsCompleteChanging(value);
					this.SendPropertyChanging();
					this._IsComplete = value;
					this.SendPropertyChanged("IsComplete");
					this.OnIsCompleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdateDate
		{
			get
			{
				return this._LastUpdateDate;
			}
			set
			{
				if ((this._LastUpdateDate != value))
				{
					this.OnLastUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateDate = value;
					this.SendPropertyChanged("LastUpdateDate");
					this.OnLastUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationGPSLon", DbType="Float NOT NULL")]
		public double DestinationGPSLon
		{
			get
			{
				return this._DestinationGPSLon;
			}
			set
			{
				if ((this._DestinationGPSLon != value))
				{
					this.OnDestinationGPSLonChanging(value);
					this.SendPropertyChanging();
					this._DestinationGPSLon = value;
					this.SendPropertyChanged("DestinationGPSLon");
					this.OnDestinationGPSLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationGPSLat", DbType="Float NOT NULL")]
		public double DestinationGPSLat
		{
			get
			{
				return this._DestinationGPSLat;
			}
			set
			{
				if ((this._DestinationGPSLat != value))
				{
					this.OnDestinationGPSLatChanging(value);
					this.SendPropertyChanging();
					this._DestinationGPSLat = value;
					this.SendPropertyChanged("DestinationGPSLat");
					this.OnDestinationGPSLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationAddress", DbType="NVarChar(1050) NOT NULL", CanBeNull=false)]
		public string DestinationAddress
		{
			get
			{
				return this._DestinationAddress;
			}
			set
			{
				if ((this._DestinationAddress != value))
				{
					this.OnDestinationAddressChanging(value);
					this.SendPropertyChanging();
					this._DestinationAddress = value;
					this.SendPropertyChanged("DestinationAddress");
					this.OnDestinationAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPaid", DbType="Bit NOT NULL")]
		public bool IsPaid
		{
			get
			{
				return this._IsPaid;
			}
			set
			{
				if ((this._IsPaid != value))
				{
					this.OnIsPaidChanging(value);
					this.SendPropertyChanging();
					this._IsPaid = value;
					this.SendPropertyChanged("IsPaid");
					this.OnIsPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostWithoutTransport", DbType="Decimal(18,2) NOT NULL")]
		public decimal CostWithoutTransport
		{
			get
			{
				return this._CostWithoutTransport;
			}
			set
			{
				if ((this._CostWithoutTransport != value))
				{
					this.OnCostWithoutTransportChanging(value);
					this.SendPropertyChanging();
					this._CostWithoutTransport = value;
					this.SendPropertyChanged("CostWithoutTransport");
					this.OnCostWithoutTransportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportCost", DbType="Decimal(18,2) NOT NULL")]
		public decimal TransportCost
		{
			get
			{
				return this._TransportCost;
			}
			set
			{
				if ((this._TransportCost != value))
				{
					this.OnTransportCostChanging(value);
					this.SendPropertyChanging();
					this._TransportCost = value;
					this.SendPropertyChanged("TransportCost");
					this.OnTransportCostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
